name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once a day at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  daily_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up git user info
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "24f1001136@ds.study.iitm.ac.in"

      - name: Add a commit with email 24f1001136@ds.study.iitm.ac.in in the name
        run: |
          # Ensure the file is always updated with a new change
          echo "Daily commit $(date)" > daily_commit.txt
          git add daily_commit.txt
          git commit -m "Automated daily commit by 24f1001136@ds.study.iitm.ac.in" || echo "No changes to commit"

      - name: Debugging - Check status
        run: |
          git status
          git log --oneline -n 5

      - name: Push changes
        run: |
          # Force push to ensure changes are pushed to the correct branch
          git push --force origin main || echo "Push failed"
