name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once a day at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  daily_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up git user info
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "24f1001136@ds.study.iitm.ac.in"

      - name: Add a commit with email 24f1001136@ds.study.iitm.ac.in
        run: |
          # Create a new commit (modify file as necessary)
          echo "Daily commit $(date)" > daily_commit.txt
          git add daily_commit.txt
          git commit -m "Automated daily commit" || echo "No changes to commit"

      - name: Push changes
        run: |
          # Ensure you're pushing to the correct branch, replace 'main' if necessary
          git push origin main || git push --force origin main
