name: Daily Commit

on:
  schedule:
    - cron: '47 2 * * *'  # Runs daily at 02:47 UTC
  workflow_dispatch:       # Allows manual trigger for testing

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 24f1001136@ds.study.iitm.ac.in
        run: echo "Daily run at $(date -u)"
        
