name: Daily Commit

on:
  schedule:
    - cron: '39 2 * * *'  # Runs daily at 02:39 UTC
  workflow_dispatch:       # Allows manual trigger for testing

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 24f1001136@ds.study.iitm.ac.in
        run: |
          echo "Daily commit at $(date -u)" >> daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily commit $(date -u)"
          git push
