name: Daily Local Commit

on:
  schedule:
    - cron: '25 3 * * *'  # Daily at 03:25 UTC
  workflow_dispatch:

jobs:
  local-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 24f1001136@ds.study.iitm.ac.in
        run: |
          echo "Daily commit at $(date -u)" >> daily-log.txt
          ls -l daily-log.txt  # Debug: confirm file exists

      - name: Commit file locally
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily commit $(date -u)" || echo "No changes to commit"
